AllCops:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb
    - bin/**/*
  Include:
    - app/controllers/cards_controller.rb
    - app/controllers/pages_controller.rb
    - app/assets/stylesheets/card.scss
    - app/models/card.rb
    - app/views/pages/index.html.erb
    - config/routes.rb

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

