AllCops:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 120

